# config/cucumber.yml
##YAML Template
---
hongmi:  IDEVICENAME='hongmi'
nubia:  IDEVICENAME='nubia'
iosdevice: IDEVICENAME='iosdevice'
iossimulator: IDEVICENAME='iossimulator'
dummy: IDEVICENAME='dummy'
